import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import TopBanner from "@/components/TopBanner";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { toast } from "sonner";

type ReceiptLineItem = {
  description: string;
  amount: number;
};

export type ReceiptPayload = {
  title: string;
  billedTo: {
    fullName: string;
    email: string;
    phone: string;
    cityState: string;
  };
  payment: {
    receiptNo: string;
    date: string;
    paymentMode: string;
    transactionId: string;
  };
  items: ReceiptLineItem[];
  totals: {
    subtotal: number;
    gstPercent: number;
    gstAmount: number;
    totalPaid: number;
  };
  notes: string;
  paymentMessage: string;
  business: {
    name: string;
    gstNo: string;
  };
  footerMessage: string;
};

const Checkout = () => {
  const [formData, setFormData] = useState<ReceiptPayload>({
    title: "Receipt",
    billedTo: {
      fullName: "",
      email: "",
      phone: "",
      cityState: "",
    },
    payment: {
      receiptNo: "",
      date: new Date().toISOString().split("T")[0],
      paymentMode: "Credit Card",
      transactionId: "",
    },
    items: [{ description: "", amount: 0 }],
    totals: {
      subtotal: 0,
      gstPercent: 18,
      gstAmount: 0,
      totalPaid: 0,
    },
    notes: "Thank you for your business!",
    paymentMessage: "Payment processed successfully.",
    business: {
      name: "Your Business Name",
      gstNo: "GSTIN123456789",
    },
    footerMessage: "Generated by AgiGrowthX",
  });

  const [isLoading, setIsLoading] = useState(false);

  // Helper to handle items change
  const handleItemChange = (index: number, field: keyof ReceiptLineItem, value: string | number) => {
    const newItems = [...formData.items];
    newItems[index] = { ...newItems[index], [field]: value };
    
    // Auto calculate totals
    const subtotal = newItems.reduce((acc, item) => acc + Number(item.amount || 0), 0);
    const gstAmount = (subtotal * formData.totals.gstPercent) / 100;
    const totalPaid = subtotal + gstAmount;

    setFormData({
      ...formData,
      items: newItems,
      totals: {
        ...formData.totals,
        subtotal,
        gstAmount,
        totalPaid,
      },
    });
  };

  const addItem = () => {
    setFormData({
      ...formData,
      items: [...formData.items, { description: "", amount: 0 }],
    });
  };

  const removeItem = (index: number) => {
    if (formData.items.length > 1) {
      const newItems = formData.items.filter((_, i) => i !== index);
      
      const subtotal = newItems.reduce((acc, item) => acc + Number(item.amount || 0), 0);
      const gstAmount = (subtotal * formData.totals.gstPercent) / 100;
      const totalPaid = subtotal + gstAmount;

      setFormData({
        ...formData,
        items: newItems,
        totals: {
          ...formData.totals,
          subtotal,
          gstAmount,
          totalPaid,
        },
      });
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      // Assuming you have an endpoint /api/receipt or similar in the backend
      const response = await fetch("http://localhost:5000/api/receipt/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        throw new Error("Failed to generate receipt");
      }

      // Handle the PDF download
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `Receipt_${formData.payment.receiptNo || 'Download'}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      
      toast.success("Receipt generated successfully!");
    } catch (error) {
      console.error(error);
      toast.error("Failed to generate receipt. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <TopBanner />
      <Navbar />
      
      <main className="flex-grow container mx-auto px-4 py-8 max-w-4xl">
        <h1 className="text-3xl font-bold mb-8">Checkout & Generate Receipt</h1>
        
        <form onSubmit={handleSubmit} className="space-y-8 bg-card p-6 md:p-8 rounded-lg shadow-sm border">
          {/* General info */}
          <div className="space-y-4">
            <h2 className="text-xl font-semibold border-b pb-2">Business & Receipt Title</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
               <div>
                  <Label>Receipt Title</Label>
                  <Input 
                    value={formData.title} 
                    onChange={e => setFormData({...formData, title: e.target.value})} 
                  />
               </div>
               <div>
                  <Label>Business Name</Label>
                  <Input 
                    value={formData.business.name} 
                    onChange={e => setFormData({...formData, business: {...formData.business, name: e.target.value}})} 
                  />
               </div>
               <div>
                  <Label>GST No</Label>
                  <Input 
                    value={formData.business.gstNo} 
                    onChange={e => setFormData({...formData, business: {...formData.business, gstNo: e.target.value}})} 
                  />
               </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {/* Billed To */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">Billed To</h2>
              <div className="space-y-4">
                <div>
                  <Label>Full Name</Label>
                  <Input 
                    required 
                    value={formData.billedTo.fullName} 
                    onChange={e => setFormData({...formData, billedTo: {...formData.billedTo, fullName: e.target.value}})} 
                  />
                </div>
                <div>
                  <Label>Email</Label>
                  <Input 
                    type="email" 
                    required 
                    value={formData.billedTo.email} 
                    onChange={e => setFormData({...formData, billedTo: {...formData.billedTo, email: e.target.value}})} 
                  />
                </div>
                <div>
                  <Label>Phone</Label>
                  <Input 
                    required 
                    value={formData.billedTo.phone} 
                    onChange={e => setFormData({...formData, billedTo: {...formData.billedTo, phone: e.target.value}})} 
                  />
                </div>
                <div>
                  <Label>City / State</Label>
                  <Input 
                    required 
                    value={formData.billedTo.cityState} 
                    onChange={e => setFormData({...formData, billedTo: {...formData.billedTo, cityState: e.target.value}})} 
                  />
                </div>
              </div>
            </div>

            {/* Payment Info */}
            <div className="space-y-4">
              <h2 className="text-xl font-semibold border-b pb-2">Payment Info</h2>
              <div className="space-y-4">
                <div>
                  <Label>Receipt No.</Label>
                  <Input 
                    required 
                    value={formData.payment.receiptNo} 
                    onChange={e => setFormData({...formData, payment: {...formData.payment, receiptNo: e.target.value}})} 
                  />
                </div>
                <div>
                  <Label>Date</Label>
                  <Input 
                    type="date"
                    required 
                    value={formData.payment.date} 
                    onChange={e => setFormData({...formData, payment: {...formData.payment, date: e.target.value}})} 
                  />
                </div>
                <div>
                  <Label>Payment Mode</Label>
                  <Input 
                    required 
                    value={formData.payment.paymentMode} 
                    onChange={e => setFormData({...formData, payment: {...formData.payment, paymentMode: e.target.value}})} 
                  />
                </div>
                <div>
                  <Label>Transaction ID</Label>
                  <Input 
                    value={formData.payment.transactionId} 
                    onChange={e => setFormData({...formData, payment: {...formData.payment, transactionId: e.target.value}})} 
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Items */}
          <div className="space-y-4">
            <h2 className="text-xl font-semibold border-b pb-2">Items</h2>
            {formData.items.map((item, index) => (
              <div key={index} className="flex gap-4 items-end">
                <div className="flex-grow">
                  <Label>Description</Label>
                  <Input 
                    required
                    value={item.description} 
                    onChange={e => handleItemChange(index, "description", e.target.value)} 
                    placeholder="E.g. MBA Consulting"
                  />
                </div>
                <div className="w-32">
                  <Label>Amount</Label>
                  <Input 
                    type="number" 
                    required
                    value={item.amount || ""} 
                    onChange={e => handleItemChange(index, "amount", parseFloat(e.target.value))} 
                    placeholder="0.00"
                  />
                </div>
                <Button type="button" variant="destructive" onClick={() => removeItem(index)} disabled={formData.items.length === 1}>
                  Remove
                </Button>
              </div>
            ))}
            <Button type="button" variant="outline" onClick={addItem}>Add Item</Button>
          </div>

          {/* Totals */}
          <div className="space-y-4 bg-muted/50 p-4 rounded-lg">
            <h2 className="text-xl font-semibold border-b pb-2">Totals</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
              <div>
                <Label>Subtotal</Label>
                <Input type="number" disabled value={formData.totals.subtotal} className="font-bold" />
              </div>
              <div>
                <Label>GST Percent (%)</Label>
                <Input 
                  type="number" 
                  value={formData.totals.gstPercent} 
                  onChange={e => {
                    const percent = parseFloat(e.target.value) || 0;
                    const subtotal = formData.totals.subtotal;
                    const gstAmount = (subtotal * percent) / 100;
                    const totalPaid = subtotal + gstAmount;
                    setFormData({
                      ...formData,
                      totals: { ...formData.totals, gstPercent: percent, gstAmount, totalPaid }
                    });
                  }} 
                />
              </div>
              <div>
                <Label>GST Amount</Label>
                <Input type="number" disabled value={formData.totals.gstAmount} className="font-bold" />
              </div>
              <div>
                <Label>Total Paid</Label>
                <Input type="number" disabled value={formData.totals.totalPaid} className="font-bold border-primary" />
              </div>
            </div>
          </div>

          {/* Notes and Messages */}
          <div className="space-y-4">
            <h2 className="text-xl font-semibold border-b pb-2">Additional Information</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
               <div>
                  <Label>Notes</Label>
                  <Textarea 
                    value={formData.notes} 
                    onChange={e => setFormData({...formData, notes: e.target.value})} 
                  />
               </div>
               <div>
                  <Label>Payment Message</Label>
                  <Textarea 
                    value={formData.paymentMessage} 
                    onChange={e => setFormData({...formData, paymentMessage: e.target.value})} 
                  />
               </div>
               <div className="md:col-span-2">
                  <Label>Footer Message</Label>
                  <Input 
                    value={formData.footerMessage} 
                    onChange={e => setFormData({...formData, footerMessage: e.target.value})} 
                  />
               </div>
            </div>
          </div>

          <Button type="submit" size="lg" className="w-full text-lg" disabled={isLoading}>
            {isLoading ? "Generating..." : "Generate Receipt"}
          </Button>
        </form>
      </main>

      <Footer />
    </div>
  );
};

export default Checkout;